# Query for the logged in user.
#import "../../../fragments/messageDetails.gql"
query validPasswordResetToken($input: PasswordResetInput) {
    validPasswordResetToken (input: $input) {
        ...messageDetails
    }
}
